# Site settings
title: Lei Zang's Blog
email: zanglei.register@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Welcome to my homepage!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 404
github_username:  leiatpku

# Build settings
markdown: kramdown
